grandnode2-2.2.x/src/Web/Grand.Web.Admin/Models/Vendors/VendorListModel.cs
using Grand.Infrastructure.ModelBinding;
using Grand.Infrastructure.Models;

namespace Grand.Web.Admin.Models.Vendors;

public class VendorListModel : BaseModel
{
    [GrandResourceDisplayName("Admin.Vendors.List.SearchName")]

    public string SearchName { get; set; }
}

grandnode2-2.2.x/src/Web/Grand.Web.Admin/Models/Vendors/VendorModel.cs
using Grand.Infrastructure.ModelBinding;
using Grand.Infrastructure.Models;
using Grand.Web.Admin.Models.Common;
using Grand.Web.Admin.Models.Discounts;
using Grand.Web.Common.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace Grand.Web.Admin.Models.Vendors;

public class VendorModel : BaseEntityModel, ILocalizedModel<VendorLocalizedModel>
{
    public VendorModel()
    {
        if (PageSize < 1) PageSize = 5;
        Locales = new List<VendorLocalizedModel>();
        AssociatedCustomers = new List<AssociatedCustomerInfo>();
        Address = new AddressModel();
        AvailableStores = new List<SelectListItem>();
    }

    [GrandResourceDisplayName("Admin.Vendors.Fields.Name")]

    public string Name { get; set; }

    [GrandResourceDisplayName("Admin.Vendors.Fields.Email")]

    public string Email { get; set; }

    [GrandResourceDisplayName("Admin.Vendors.Fields.Description")]

    public string Description { get; set; }

    [UIHint("Picture")]
    [GrandResourceDisplayName("Admin.Vendors.Fields.Picture")]
    public string PictureId { get; set; }

    [GrandResourceDisplayName("Admin.Vendors.Fields.Store")]
    public string StoreId { get; set; }

    public List<SelectListItem> AvailableStores { get; set; }

    [GrandResourceDisplayName("Admin.Vendors.Fields.AdminComment")]

    public string AdminComment { get; set; }

    [GrandResourceDisplayName("Admin.Vendors.Fields.Active")]
    public bool Active { get; set; }

    [GrandResourceDisplayName("Admin.Vendors.Fields.DisplayOrder")]
    public int DisplayOrder { get; set; }

    [GrandResourceDisplayName("Admin.Vendors.Fields.AllowCustomerReviews")]
    public bool AllowCustomerReviews { get; set; }

    [GrandResourceDisplayName("Admin.Vendors.Fields.MetaKeywords")]

    public string MetaKeywords { get; set; }

    [GrandResourceDisplayName("Admin.Vendors.Fields.MetaDescription")]

    public string MetaDescription { get; set; }

    [GrandResourceDisplayName("Admin.Vendors.Fields.MetaTitle")]

    public string MetaTitle { get; set; }

    [GrandResourceDisplayName("Admin.Vendors.Fields.SeName")]

    public string SeName { get; set; }

    [GrandResourceDisplayName("Admin.Vendors.Fields.PageSize")]
    public int PageSize { get; set; }

    [GrandResourceDisplayName("Admin.Vendors.Fields.AllowCustomersToSelectPageSize")]
    public bool AllowCustomersToSelectPageSize { get; set; }

    [GrandResourceDisplayName("Admin.Vendors.Fields.PageSizeOptions")]
    public string PageSizeOptions { get; set; }

    [GrandResourceDisplayName("Admin.Vendors.Fields.AssociatedCustomerEmails")]
    public IList<AssociatedCustomerInfo> AssociatedCustomers { get; set; }

    public AddressModel Address { get; set; }

    //vendor notes
    [GrandResourceDisplayName("Admin.Vendors.VendorNotes.Fields.Note")]

    public string AddVendorNoteMessage { get; set; }

    public List<DiscountModel> AvailableDiscounts { get; set; }
    public string[] SelectedDiscountIds { get; set; }

    [GrandResourceDisplayName("Admin.Vendors.Fields.Commission")]
    public double? Commission { get; set; }

    public IList<VendorLocalizedModel> Locales { get; set; }

    #region Nested classes

    public class AssociatedCustomerInfo : BaseEntityModel
    {
        public string Email { get; set; }
    }


    public class VendorNote : BaseEntityModel
    {
        public string VendorId { get; set; }

        [GrandResourceDisplayName("Admin.Vendors.VendorNotes.Fields.Note")]
        public string Note { get; set; }

        [GrandResourceDisplayName("Admin.Vendors.VendorNotes.Fields.CreatedOn")]
        public DateTime CreatedOn { get; set; }
    }

    #endregion
}

public class VendorLocalizedModel : ILocalizedModelLocal, ISlugModelLocal
{
    [GrandResourceDisplayName("Admin.Vendors.Fields.Name")]

    public string Name { get; set; }

    [GrandResourceDisplayName("Admin.Vendors.Fields.Description")]

    public string Description { get; set; }

    [GrandResourceDisplayName("Admin.Vendors.Fields.MetaKeywords")]

    public string MetaKeywords { get; set; }

    [GrandResourceDisplayName("Admin.Vendors.Fields.MetaDescription")]

    public string MetaDescription { get; set; }

    [GrandResourceDisplayName("Admin.Vendors.Fields.MetaTitle")]

    public string MetaTitle { get; set; }

    public string LanguageId { get; set; }

    [GrandResourceDisplayName("Admin.Vendors.Fields.SeName")]

    public string SeName { get; set; }
}

grandnode2-2.2.x/src/Web/Grand.Web.Admin/Models/Vendors/VendorReviewListModel.cs
using Grand.Infrastructure.ModelBinding;
using Grand.Infrastructure.Models;
using System.ComponentModel.DataAnnotations;

namespace Grand.Web.Admin.Models.Vendors;

public class VendorReviewListModel : BaseModel
{
    [GrandResourceDisplayName("Admin.VendorReviews.List.CreatedOnFrom")]
    [UIHint("DateNullable")]
    public DateTime? CreatedOnFrom { get; set; }

    [GrandResourceDisplayName("Admin.VendorReviews.List.CreatedOnTo")]
    [UIHint("DateNullable")]
    public DateTime? CreatedOnTo { get; set; }

    [GrandResourceDisplayName("Admin.VendorReviews.List.SearchText")]
    public string SearchText { get; set; }

    [GrandResourceDisplayName("Admin.VendorReviews.List.SearchVendor")]
    public string SearchVendorId { get; set; }
}

grandnode2-2.2.x/src/Web/Grand.Web.Admin/Models/Vendors/VendorReviewModel.cs
using Grand.Infrastructure.ModelBinding;
using Grand.Infrastructure.Models;

namespace Grand.Web.Admin.Models.Vendors;

public class VendorReviewModel : BaseEntityModel
{
    [GrandResourceDisplayName("Admin.VendorReviews.Fields.Vendor")]
    public string VendorId { get; set; }

    [GrandResourceDisplayName("Admin.VendorReviews.Fields.Vendor")]
    public string VendorName { get; set; }

    public string Ids => Id + ":" + VendorId;

    [GrandResourceDisplayName("Admin.VendorReviews.Fields.Customer")]
    public string CustomerId { get; set; }

    [GrandResourceDisplayName("Admin.VendorReviews.Fields.Customer")]
    public string CustomerInfo { get; set; }

    [GrandResourceDisplayName("Admin.VendorReviews.Fields.Title")]
    public string Title { get; set; }

    [GrandResourceDisplayName("Admin.VendorReviews.Fields.ReviewText")]
    public string ReviewText { get; set; }

    [GrandResourceDisplayName("Admin.VendorReviews.Fields.Rating")]
    public int Rating { get; set; }

    [GrandResourceDisplayName("Admin.VendorReviews.Fields.IsApproved")]
    public bool IsApproved { get; set; }

    [GrandResourceDisplayName("Admin.VendorReviews.Fields.CreatedOn")]
    public DateTime CreatedOn { get; set; }
}

grandnode2-2.2.x/src/Web/Grand.Web.Admin/Controllers/VendorController.cs
using Grand.Business.Core.Commands.Customers;
using Grand.Business.Core.Extensions;
using Grand.Business.Core.Interfaces.Common.Localization;
using Grand.Business.Core.Interfaces.Customers;
using Grand.Business.Core.Utilities.Common.Security;
using Grand.Web.Admin.Extensions.Mapping;
using Grand.Web.Admin.Interfaces;
using Grand.Web.Admin.Models.Vendors;
using Grand.Web.Common.DataSource;
using Grand.Web.Common.Filters;
using Grand.Web.Common.Security.Authorization;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace Grand.Web.Admin.Controllers;

[PermissionAuthorize(PermissionSystemName.Vendors)]
public class VendorController : BaseAdminController
{
    #region Constructors

    public VendorController(
        IVendorViewModelService vendorViewModelService,
        ITranslationService translationService,
        IVendorService vendorService,
        ILanguageService languageService,
        IMediator mediator)
    {
        _vendorViewModelService = vendorViewModelService;
        _translationService = translationService;
        _vendorService = vendorService;
        _languageService = languageService;
        _mediator = mediator;
    }

    #endregion

    #region Reviews

    [PermissionAuthorizeAction(PermissionActionName.Preview)]
    [HttpPost]
    public async Task<IActionResult> Reviews(DataSourceRequest command, string vendorId)
    {
        var vendor = await _vendorService.GetVendorById(vendorId);
        if (vendor == null)
            throw new ArgumentException("No vendor found with the specified id");

        var vendorReviews = await _vendorService.GetAllVendorReviews("", null,
            null, null, "", vendorId, command.Page - 1, command.PageSize);
        var items = new List<VendorReviewModel>();
        foreach (var item in vendorReviews)
        {
            var m = new VendorReviewModel();
            await _vendorViewModelService.PrepareVendorReviewModel(m, item, false, true);
            items.Add(m);
        }

        var gridModel = new DataSourceResult {
            Data = items,
            Total = vendorReviews.TotalCount
        };

        return Json(gridModel);
    }

    #endregion

    #region Fields

    private readonly IVendorViewModelService _vendorViewModelService;
    private readonly ITranslationService _translationService;
    private readonly IVendorService _vendorService;
    private readonly ILanguageService _languageService;
    private readonly IMediator _mediator;

    #endregion

    #region Methods

    //list
    public IActionResult Index()
    {
        return RedirectToAction("List");
    }

    public IActionResult List()
    {
        var model = new VendorListModel();
        return View(model);
    }

    [PermissionAuthorizeAction(PermissionActionName.List)]
    [HttpPost]
    public async Task<IActionResult> List(DataSourceRequest command, VendorListModel model)
    {
        var vendors = await _vendorService.GetAllVendors(model.SearchName, command.Page - 1, command.PageSize, true);
        var gridModel = new DataSourceResult {
            Data = vendors.Select(x =>
            {
                var vendorModel = x.ToModel();
                return vendorModel;
            }),
            Total = vendors.TotalCount
        };
        return Json(gridModel);
    }

    //create
    [PermissionAuthorizeAction(PermissionActionName.Create)]
    public async Task<IActionResult> Create()
    {
        var model = await _vendorViewModelService.PrepareVendorModel();
        //locales
        await AddLocales(_languageService, model.Locales);
        return View(model);
    }

    [PermissionAuthorizeAction(PermissionActionName.Edit)]
    [HttpPost]
    [ArgumentNameFilter(KeyName = "save-continue", Argument = "continueEditing")]
    public async Task<IActionResult> Create(VendorModel model, bool continueEditing)
    {
        if (ModelState.IsValid)
        {
            var vendor = await _vendorViewModelService.InsertVendorModel(model);
            Success(_translationService.GetResource("Admin.Vendors.Added"));
            return continueEditing ? RedirectToAction("Edit", new { id = vendor.Id }) : RedirectToAction("List");
        }

        //prepare address model
        await _vendorViewModelService.PrepareVendorAddressModel(model, null);
        //discounts
        await _vendorViewModelService.PrepareDiscountModel(model, null, true);
        //stores
        await _vendorViewModelService.PrepareStore(model);

        //If we got this far, something failed, redisplay form
        return View(model);
    }


    //edit
    [PermissionAuthorizeAction(PermissionActionName.Preview)]
    public async Task<IActionResult> Edit(string id)
    {
        var vendor = await _vendorService.GetVendorById(id);
        if (vendor == null || vendor.Deleted)
            //No vendor found with the specified id
            return RedirectToAction("List");

        var model = vendor.ToModel();
        //locales
        await AddLocales(_languageService, model.Locales, (locale, languageId) =>
        {
            locale.Name = vendor.GetTranslation(x => x.Name, languageId, false);
            locale.Description = vendor.GetTranslation(x => x.Description, languageId, false);
            locale.MetaKeywords = vendor.GetTranslation(x => x.MetaKeywords, languageId, false);
            locale.MetaDescription = vendor.GetTranslation(x => x.MetaDescription, languageId, false);
            locale.MetaTitle = vendor.GetTranslation(x => x.MetaTitle, languageId, false);
            locale.SeName = vendor.GetSeName(languageId, false);
        });
        //discounts
        await _vendorViewModelService.PrepareDiscountModel(model, vendor, false);
        //associated customer emails
        model.AssociatedCustomers = await _vendorViewModelService.AssociatedCustomers(vendor.Id);
        //prepare address model
        await _vendorViewModelService.PrepareVendorAddressModel(model, vendor);
        //stores
        await _vendorViewModelService.PrepareStore(model);

        return View(model);
    }

    [PermissionAuthorizeAction(PermissionActionName.Edit)]
    [HttpPost]
    [ArgumentNameFilter(KeyName = "save-continue", Argument = "continueEditing")]
    public async Task<IActionResult> Edit(VendorModel model, bool continueEditing)
    {
        var vendor = await _vendorService.GetVendorById(model.Id);
        if (vendor == null || vendor.Deleted)
            //No vendor found with the specified id
            return RedirectToAction("List");

        if (ModelState.IsValid)
        {
            vendor = await _vendorViewModelService.UpdateVendorModel(vendor, model);

            Success(_translationService.GetResource("Admin.Vendors.Updated"));
            if (continueEditing)
            {
                //selected tab
                await SaveSelectedTabIndex();

                return RedirectToAction("Edit", new { id = vendor.Id });
            }

            return RedirectToAction("List");
        }

        //If we got this far, something failed, redisplay form
        //discounts
        await _vendorViewModelService.PrepareDiscountModel(model, vendor, true);
        //prepare address model
        await _vendorViewModelService.PrepareVendorAddressModel(model, vendor);
        //associated customer emails
        model.AssociatedCustomers = await _vendorViewModelService.AssociatedCustomers(vendor.Id);
        //stores
        await _vendorViewModelService.PrepareStore(model);

        return View(model);
    }


    [PermissionAuthorizeAction(PermissionActionName.Edit)]
    [HttpPost]
    public async Task<IActionResult> Activate(string id, string activatevendor)
    {
        var vendor = await _vendorService.GetVendorById(id);
        if (vendor == null || vendor.Deleted)
            //No vendor found with the specified id
            return RedirectToAction("List");

        var associatedCustomers = await _vendorViewModelService.AssociatedCustomers(vendor.Id);
        if (!associatedCustomers.Any())
        {
            Error(_translationService.GetResource("Admin.Vendors.Fields.AssociatedCustomerEmails.None"));
            return RedirectToAction("Edit", new { id = vendor.Id });
        }

        var activate = await _mediator.Send(new ActiveVendorCommand {
            Vendor = vendor,
            Active = activatevendor == "active",
            CustomerIds = associatedCustomers.Select(x => x.Id).ToList()
        });

        if (activate)
            Success(_translationService.GetResource("Admin.Vendors.Updated"));

        return RedirectToAction("Edit", new { id = vendor.Id });
    }

    //delete
    [PermissionAuthorizeAction(PermissionActionName.Delete)]
    [HttpPost]
    public async Task<IActionResult> Delete(string id)
    {
        var vendor = await _vendorService.GetVendorById(id);
        if (vendor == null)
            //No vendor found with the specified id
            return RedirectToAction("List");

        if (ModelState.IsValid)
        {
            await _vendorViewModelService.DeleteVendor(vendor);
            Success(_translationService.GetResource("Admin.Vendors.Deleted"));
            return RedirectToAction("List");
        }

        Error(ModelState);
        return RedirectToAction("Edit", new { id = vendor.Id });
    }

    #endregion

    #region Vendor notes

    [PermissionAuthorizeAction(PermissionActionName.Preview)]
    [HttpPost]
    public async Task<IActionResult> VendorNotesSelect(string vendorId, DataSourceRequest command)
    {
        var vendor = await _vendorService.GetVendorById(vendorId);
        if (vendor == null)
            throw new ArgumentException("No vendor found with the specified id");

        var vendorNoteModels = _vendorViewModelService.PrepareVendorNote(vendor);
        var gridModel = new DataSourceResult {
            Data = vendorNoteModels,
            Total = vendorNoteModels.Count
        };

        return Json(gridModel);
    }

grandnode2-2.2.x/src/Web/Grand.Web.Admin/Areas/Admin/Views/Vendor/Partials/CreateOrUpdate.TabDiscounts.cshtml
@model VendorModel
@{
    if (Model.AvailableDiscounts is { Count: > 0 })
    {
        <div class="mt-checkbox-list">
            @foreach (var discount in Model.AvailableDiscounts)
            {
                <label class="mt-checkbox mt-checkbox-outline control control-checkbox">
                    <input type="checkbox" name="SelectedDiscountIds" value="@discount.Id"
                           @if (Model.SelectedDiscountIds != null && Model.SelectedDiscountIds.Contains(discount.Id))
                           {
                               <text> checked="checked" </text>
                           }/>@discount.Name
                    <div class="control__indicator"></div>
                </label>
            }
        </div>
    }
    else
    {
        <div class="note note-info">
            @Html.Raw(Loc["Admin.Vendors.Discounts.NoDiscounts"])
        </div>
    }
}

grandnode2-2.2.x/src/Web/Grand.Web.Admin/Areas/Admin/Views/Vendor/Partials/CreateOrUpdate.TabDocuments.cshtml
@model VendorModel
@inject AdminAreaSettings adminAreaSettings
@if (!string.IsNullOrEmpty(Model.Id))
{
    <div class="panel panel-default">
        <vc:admin-widget widget-zone="vendor_details_documents_top" additional-data="Model"/>
        <div class="panel-body">
            <div id="vendor-documents-grid"></div>
        </div>
        <div class="panel-footer">
            <button type="button" class="k-button" onclick="location.href='@Url.Action("CreateDocument", "Document", new { ObjectId = Model.Id, Reference = (int)Reference.Vendor, area = Constants.AreaAdmin })'"><i class="fa fa-plus"></i>&nbsp;@Loc["Admin.Marketing.Document.Add"]</button>
        </div>
        <vc:admin-widget widget-zone="vendor_details_documents_bottom" additional-data="Model"/>
    </div>

    <script>
        $(document).ready(function () {
            $("#vendor-documents-grid").kendoGrid({
                dataSource: {
                    transport: {
                        read: {
                            url: "@Html.Raw(Url.Action("ListDocuments", "Document", new { reference = (int)Reference.Vendor, ObjectId = Model.Id, StatusId = -1, area = Constants.AreaAdmin }))",
                            type: "POST",
                            dataType: "json",
                            data: addAntiForgeryToken
                        },
                    },
                    schema: {
                        data: "Data",
                        total: "Total",
                        errors: "Errors",
                    },
                    error: function(e) {
                        display_kendoui_grid_error(e);
                        // Cancel the changes
                        this.cancelChanges();
                    },
                    pageSize: @(adminAreaSettings.DefaultGridPageSize),
                    serverPaging: true,
                    serverFiltering: true,
                    serverSorting: true
                },
                autoBind: false,
                pageable: {
                    refresh: true,
                    pageSizes: [@(adminAreaSettings.GridPageSizes)]
                },
                editable: {
                    confirmation: true,
                    mode: "inline"
                },
                scrollable: false,
                columns: [{
                        field: "Number",
                        title: "@Loc["Admin.Documents.Document.Fields.Number"]",
                        template: '<a class="k-link" href="@Url.Action("EditDocument", "Document", new { area = Constants.AreaAdmin })/#=Id#">#=kendo.htmlEncode(Number)#</a>',
                    },
                    {
                        field: "Name",
                        title: "@Loc["Admin.Documents.Document.Fields.Name"]",
                        template: '<a class="k-link" href="@Url.Action("EditDocument", "Document", new { area = Constants.AreaAdmin })/#=Id#">#=kendo.htmlEncode(Name)#</a>',
                    }, {
                        field: "Published",
                        title: "@Loc["Admin.Documents.Document.Fields.Published"]",
                        width: 100,
                        minScreenWidth: 500,
                        headerAttributes: { style: "text-align:center" },
                        attributes: { style: "text-align:center" },
                        template: '# if(Published) {# <i class="fa fa-check" aria-hidden="true" style="color:green"></i> #} else {# <i class="fa fa-times" aria-hidden="true" style="color:red"></i> #} #'
                }]
            });
        });
    </script>
}
else
{
    <div class="note note-info">
        @Loc["Admin.Catalog.SaveBeforeEdit"]
    </div>
}

grandnode2-2.2.x/src/Web/Grand.Web.Admin/Areas/Admin/Views/Vendor/Partials/CreateOrUpdate.TabVendorNotes.cshtml
@model VendorModel

<div id="vendornotes-grid"></div>
<script>
    $(document).ready(function () {
        $("#vendornotes-grid").kendoGrid({
            dataSource: {
                transport: {
                    read: {
                        url: "@Html.Raw(Url.Action("VendorNotesSelect", "Vendor", new { vendorId = Model.Id, area = Constants.AreaAdmin }))",
                        type: "POST",
                        dataType: "json",
                        data: addAntiForgeryToken
                    },
                    destroy: {
                        url: "@Html.Raw(Url.Action("VendorNoteDelete", "Vendor", new { vendorId = Model.Id, area = Constants.AreaAdmin }))",
                        type: "POST",
                        dataType: "json",
                        data: addAntiForgeryToken
                    }
                },
                schema: {
                    data: "Data",
                    total: "Total",
                    errors: "Errors",
                    model: {
                        id: "Id",
                        fields: {
                            //do not implicitly specify all fields
                            //we do it only for fields which implicitly require it
                            //otherwise, they'll be formatted wrong way
                            CreatedOn: {type: "date" }
                        }
                    }
                },
                error: function(e) {
                    display_kendoui_grid_error(e);
                    // Cancel the changes
                    this.cancelChanges();
                },
                serverPaging: true,
                serverFiltering: true,
                serverSorting: true
            },
            autoBind: false,
            pageable: {
                refresh: true,
                numeric: false,
                previousNext: false,
                info: false
            },
            editable: {
                confirmation: false,
                mode: "inline"
            },
            scrollable: false,
            columns: [{
                field: "CreatedOn",
                title: "@Loc["Admin.Vendors.VendorNotes.Fields.CreatedOn"]",
                width: 200,
                type: "date",
                format: "{0:G}"
            }, {
                field: "Note",
                title: "@Loc["Admin.Vendors.VendorNotes.Fields.Note"]",
                encoded: false
            }, {
                command: { name: "destroy", text: "@Loc["Admin.Common.Delete"]" },
                title: "@Loc["Admin.Common.Delete"]",
                width: 100
            }]
        });
    });
</script>
<p>
    <strong>
        @Loc["Admin.Vendors.VendorNotes.AddTitle"]
    </strong>
</p>
<div class="form-horizontal">
    <vc:admin-widget widget-zone="vendor_details_notes_top" additional-data="Model"/>
    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="AddVendorNoteMessage"/>
            <div class="col-md-9 col-sm-9">
                <admin-textarea asp-for="AddVendorNoteMessage" style="height: 100px;"></admin-textarea>
                <span asp-validation-for="AddVendorNoteMessage"></span>
            </div>
        </div>
    </div>
    <div class="actions">
        <div class="offset-md-3 offset-sm-3 col-md-9 col-sm-9">
            <input type="button" id="addVendorNote" class="k-button" value="@Loc["Admin.Vendors.VendorNotes.AddButton"]"/>
        </div>
    </div>
    <vc:admin-widget widget-zone="vendor_details_notes_bottom" additional-data="Model"/>
</div>
<script>
    $(document).ready(function () {
        $('#addVendorNote').click(function () {
            var vendorNoteMessage = $("#@Html.IdFor(model => model.AddVendorNoteMessage)").val();
            $('#addVendorNote').attr('disabled', true);

            var postData = {
                message: vendorNoteMessage,
                vendorId: '@Model.Id'
            };
            addAntiForgeryToken(postData);

            $.ajax({
                cache: false,
                type: "POST",
                url: "@(Url.Action("VendorNoteAdd", "Vendor", new { area = Constants.AreaAdmin }))",
                data: postData,
                success: function (data) {
                    var grid = $("#vendornotes-grid").data('kendoGrid');
                    grid.dataSource.read();
                    $('#addVendorNote').attr('disabled', false);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Failed to add vendor note.');
                    $('#addVendorNote').attr('disabled', false);
                }
            });
        });
    });
</script>

grandnode2-2.2.x/src/Web/Grand.Web.Admin/Areas/Admin/Views/Vendor/Partials/CreateOrUpdate.TabVendorReviews.cshtml
@model VendorModel
@inject AdminAreaSettings adminAreaSettings

<div class="panel panel-default">
    <vc:admin-widget widget-zone="vendor_details_reviews_top" additional-data="Model"/>
    <div class="panel-body">
        <div id="reviews-grid"></div>
    </div>
    <vc:admin-widget widget-zone="vendor_details_reviews_bottom" additional-data="Model"/>
</div>
<script>
$(document).ready(function () {
    $("#reviews-grid").kendoGrid({
        dataSource: {
            transport: {
                read: {
                    url: "@Html.Raw(Url.Action("Reviews", "Vendor", new { VendorId = Model.Id, area = Constants.AreaAdmin }))",
                    type: "POST",
                    dataType: "json",
                    data: addAntiForgeryToken
                }
            },
            schema: {
                data: "Data",
                total: "Total",
                errors: "Errors"
            },
            error: function(e) {
                display_kendoui_grid_error(e);
                // Cancel the changes
                this.cancelChanges();
            },
            pageSize: @(adminAreaSettings.DefaultGridPageSize),
            serverPaging: true,
            serverFiltering: true,
            serverSorting: true
        },
        autoBind: false,
        pageable: {
            refresh: true,
            pageSizes: [@(adminAreaSettings.GridPageSizes)]
        },
        editable: {
            confirmation: false,
            mode: "inline"
        },
        scrollable: false,
        columns: [{
            field: "CustomerId",
            title: "@Loc["Admin.VendorReviews.Fields.Customer"]",
            width: 200,
            template: '<a href="@Url.Action("Edit", "Customer", new { area = Constants.AreaAdmin })/#=CustomerId#">#:kendo.htmlEncode(CustomerInfo)#</a>'
        },
        {
            field: "Title",
            encoded: false,
            title: "@Loc["Admin.VendorReviews.Fields.Title"]",
            width: 300
        },
        {
            field: "Rating",
            title: "@Loc["Admin.VendorReviews.Fields.Rating"]",
            width: 100
        },
        {
            field: "IsApproved",
            title: "@Loc["Admin.VendorReviews.Fields.IsApproved"]",
            width: 100,
            headerAttributes: { style: "text-align:center" },
            attributes: { style: "text-align:center" },
            template: '# if(IsApproved) {# <i class="fa fa-check" aria-hidden="true" style="color:green"></i> #} else {# <i class="fa fa-times" aria-hidden="true" style="color:red"></i> #} #'
        },
        {
            field: "CreatedOn",
            title: "@Loc["Admin.Orders.Fields.CreatedOn"]",
            width: 200,
            type: "date",
            format: "{0:G}"
        },
        {
            field: "Id",
            title: "@Loc["Admin.Common.View"]",
            width: 100,
            template: '<a class="btn btn-sm btn-default" href="@Url.Action("Edit", "VendorReview", new { area = Constants.AreaAdmin })/#=Id#"><i class="fa fa-search"></i> @Loc["Admin.Common.View"]</a>'
        }]
    });
});
</script>